### ISSUE TITLE
uninitialized constant Psych::Syck::PrivateType when requiring r18n-core in Shoes

### ISSUE THREAD

**Issue by apjanke** [r18n/r18n#210] opened 2019-05-28 03:49 UTC
Hi, r18n folks,

I'm getting a weird error when trying to use the `r18n-core` gem under [Shoes](http://shoesrb.com/).

Here's the entirety of my Shoes app, `load_r18n_core.rb`:

```
Shoes.setup do
  gem "r18n-core"
end

require "r18n-core"

Shoes.app do
  button "Push me"
end
```

When I run it under Shoes 3.3.7, at the point where it does the `require "r18n-core"`, it raises this error:

```
Error in <unknown> line 0 | 2019-05-27 23:30:45 -0400
uninitialized constant Psych::Syck::PrivateType
Did you mean?  Psych::PrivateType
/Users/janke/.shoes/+gem/gems/r18n-core-3.2.0/lib/r18n-core/yaml_methods.rb:28:in `detect_yaml_private_type'
[...]
```

<img width="898" alt="Screen Shot 2019-05-27 at 11 46 42 PM" src="https://user-images.githubusercontent.com/2618447/58449474-b128a400-80d9-11e9-9286-dc3a18d03d67.png">

Lines 27-29 of `yaml_methods.rb` are this:

```
    def detect_yaml_private_type
      @private_type_class = ::Syck::PrivateType if defined?(Syck)
    end
```

It's not happening under regular Ruby. I can require `r18n-core` and `r18n-desktop` there just fine. I've also asked on the Shoes repo since it's specific to that environment (https://github.com/shoes/shoes3/issues/443), but we haven't been able to figure it out there either.

Do you have any idea what's going on here? I thought the expression `::Syck` with nothing to the left of the `::` would look in the global namespace (or the `Object` namespace?). So why would it be looking in the `Psych` namespace for `Syck`?

This is on macOS 10.14.5.

**Comment by AlexWayfer** [comment] 2019-05-28 08:23
Hello!

Thank you for report.

What version of Shoes are you using?

I'm following the instructions from Shoes repo for v4 (install `jruby`, `gem install shoes --pre`, `ruby test.rb` with content from your comment) and can't reproduce (there is a window with button and without errors) on Linux.

But I guess there is a problem because of `defined?(Syck)` without only-root look-up. So, if there is `Something::Syck` defined, `defined?(Syck)` may return `true`, but `::Syck` will raise an error.

**Comment by AlexWayfer** [comment] 2020-01-27 14:26
I'm going to close this without requested info.

**Comment by AlexWayfer** [comment] 2021-02-05 23:42
Sorry, I don't know what to do. 🤷

**Closed by AlexWayfer** 2021-02-05 23:42 UTC

**Comment by apjanke** [comment] 2021-02-10 18:37
Oh, hi! Sorry, I missed your previous comments; must have gotten lost in my inbox.

Ah, don't worry about it: I've given up on this project; couldn't get Shoes to work reliably. You can just leave this closed.

**Comment by AlexWayfer** [comment] 2021-02-10 21:21
> Oh, hi! Sorry, I missed your previous comments; must have gotten lost in my inbox.
> 
> Ah, don't worry about it: I've given up on this project; couldn't get Shoes to work reliably. You can just leave this closed.

OK, I just want to clarify if somebody will face with a similar issue — don't hesitate to write here.
