### ISSUE TITLE
R18n::Translated and Sinatra

### ISSUE THREAD

**Issue by rickthomasjr** [r18n/r18n#30] opened 2011-06-23 19:31 UTC
I have an api running on Sinatra that has active record models using R18n::Translated.  I'm having some major consistency issues with this feature - sometimes the correct translation returns, sometimes it's english.  Is there some way I can explicitly set the desired local when I instantiate one of these models?

Please help!  I love this gem, and I would hate to re-architect my multi-lingual support.

**Comment by AlexWayfer** [comment] 2018-08-16 13:00
> P.S.: 1.10.3 is last R18n-based version so use this tag.

I can't run it. :(

```
Traceback (most recent call last):
	20: from ./local-run.rb:6:in `<main>'
	19: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	18: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	17: from /home/alex/Projects/ruby/runit-man/lib/runit-man/runner.rb:2:in `<top (required)>'
	16: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	15: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	14: from /home/alex/Projects/ruby/runit-man/lib/runit-man/app.rb:11:in `<top (required)>'
	13: from /home/alex/Projects/ruby/runit-man/lib/runit-man/app.rb:79:in `<class:RunitMan>'
	12: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1386:in `get'
	11: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1604:in `route'
	10: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1629:in `compile!'
	 9: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1641:in `compile'
	 8: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustermann-1.0.2/lib/mustermann.rb:67:in `new'
	 7: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustermann-1.0.2/lib/mustermann/pattern.rb:59:in `new'
	 6: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustermann-1.0.2/lib/mustermann/equality_map.rb:39:in `fetch'
	 5: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustermann-1.0.2/lib/mustermann/pattern.rb:59:in `block in new'
	 4: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustermann-1.0.2/lib/mustermann/pattern.rb:59:in `new'
	 3: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustermann-1.0.2/lib/mustermann/regular.rb:26:in `initialize'
	 2: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustermann-1.0.2/lib/mustermann/regexp_based.rb:19:in `initialize'
	 1: from /home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustermann-1.0.2/lib/mustermann/regular.rb:32:in `compile'
/home/alex/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustermann-1.0.2/lib/mustermann/regular.rb:41:in `check_anchors': regular expression should not contain ^: "^\\/([^\\/]+)\\/log(?:\\/(\\d+))?\\/?$" (Mustermann::CompileError)
```

**Comment by AlexWayfer** [comment] 2021-02-05 23:52
Almost 9 years, wow! Sorry, I'm going to close this issue: as I wrote earlier, I couldn't reproduce. If you still experience something similar, and especially if you can provide example — I'd be glad to re-open and resolve it.

**Closed by AlexWayfer** 2021-02-05 23:52 UTC
